version: '3'
services:
  api:
    image: node:14.15.5
    working_dir: /server
    ports: 
      - 3000:3000
    environment:
      - PORT=3000 
      - PGUSER=elwin
      - PGHOST=db
      - PGPASSWORD=hamiltonpass
      - PGDATABASE=hamilton
      - PGPORT=5432
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./api
        target: /server
    command: bash -c "npm install && npm run dev"

  db:
    image: postgres:latest
    expose:
      - "5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db/setup/:docker-entrypoint-initdb.d/:ro"
    environment: 
      - POSTGRES_DB=hamilton
      - POSTGRES_USER=elwin
      - POSTGRES_PASSWORD=hamiltonpass
volumes:
  dbdata: